name: coco-fatiando
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - jupyter
  - jupyterlab
  - jupyterlab-spellchecker
  - xarray
  - netcdf4
  - pyproj
  - pykdtree
  - numba
  - tqdm
  # Fatiando packages
  - pooch>=1.6.0,<2.0.0
  - verde>=1.6.0,<2.0.0
  - boule==0.3.*
  - harmonica==0.4.*
